### ISSUE TITLE
Popup detalja jednog stocka

### ISSUE THREAD

**Issue by rivanovic10120rn** [RAF-SI-2022/Banka-2-Frontend#105]
napraviti formu/stranicu za prikaz jedne hartije od vrednosti
prikaz treba da sadrzi:
- grafik promene cene date hartije (dan, mesec, tri meseca, sest meseci, godina, tri godine, od pocetka poslovanja)
- Detalji hartije
	- Promena (uticaj zadnje promene na cenu)
	- Open (otvorena, cena na pocetku trenutnog dana)
	- Donja granica (donja granica cene za trenutni dan)
	- Gornja granica (gornja granica cene za trenutni dan)
	- Previous close (cena na kraju prethodnog dana)
	- Dnevni opseg (Donja granica-Gornja granica)
	- Price volume (price volume = volume * akcija)
	- Kolicina/volume (kolicina koje su razmenjene na trzistu)
	- Outstanding shares (sve akcije)
	- Market Cap (vrednost firme = sve akcije * akcija)

![Image](https://user-images.githubusercontent.com/72025798/225692322-b60330c5-856c-4528-a321-a4cf4f0df3f2.png)

**Comment by SrdjanLazic** [comment]
Ostalo jos izracunati day range kada stignu podaci sa back-a i popuniti graf sa podacima sa beka
